stages:
  - install
  - build

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

install_packages:
  stage: install
  before_script:
    - whoami
    - pwd
    - locate npm
    - echo ${PATH}
    - which npm
    - ls -lh $(which npm)
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - 'package.json'
      when: always
    - when: never
  script:
    - npm i
  tags:
    - deploy

build_and_deploy:
  stage: build
  only:
    - master
  script:
    - npm run build:doc
    - echo "========== build success, start deploy ========="
    - cp -r docs-dist/* /var/www/ultra-design.hyyar.com/
  tags:
    - deploy
